import 'package:flutter/material.dart';

import '../../shared/app_widgets.dart';

class ServiceCatalogItem {
  const ServiceCatalogItem({
    required this.name,
    required this.subtitle,
    required this.asset,
    required this.icon,
    required this.tint,
    this.rating = 4.8,
    this.professionals = '80+ Professionals',
  });

  final String name;
  final String subtitle;
  final String asset;
  final IconData icon;
  final Color tint;
  final double rating;
  final String professionals;
}

class ServiceCatalogGroup {
  const ServiceCatalogGroup({
    required this.name,
    required this.subtitle,
    required this.imageAsset,
    required this.icon,
    required this.tint,
    required this.services,
  });

  final String name;
  final String subtitle;
  final String imageAsset;
  final IconData icon;
  final Color tint;
  final List<ServiceCatalogItem> services;
}

const takerServices = [
  ServiceCatalogItem(
    name: 'Electrician',
    subtitle: 'Switch, wiring, fittings',
    asset: AppAssets.serviceElectrician,
    icon: Icons.electric_bolt,
    tint: Color(0xFFFFF1D8),
    professionals: '120+ Professionals',
  ),
  ServiceCatalogItem(
    name: 'Plumber',
    subtitle: 'Leakage, taps, pipes',
    asset: AppAssets.servicePlumber,
    icon: Icons.plumbing,
    tint: Color(0xFFE9F2FF),
    professionals: '95+ Professionals',
    rating: 4.7,
  ),
  ServiceCatalogItem(
    name: 'Carpenter',
    subtitle: 'Furniture repair',
    asset: AppAssets.serviceCarpenter,
    icon: Icons.handyman,
    tint: Color(0xFFFFF4EA),
    professionals: '80+ Professionals',
    rating: 4.6,
  ),
  ServiceCatalogItem(
    name: 'Painter',
    subtitle: 'Wall paint & polish',
    asset: AppAssets.servicePainter,
    icon: Icons.format_paint,
    tint: Color(0xFFFFE8E4),
    professionals: '70+ Professionals',
    rating: 4.6,
  ),
  ServiceCatalogItem(
    name: 'AC Repair',
    subtitle: 'Service & gas refill',
    asset: AppAssets.serviceAcRepair,
    icon: Icons.ac_unit,
    tint: Color(0xFFF1F3F5),
    professionals: '65+ Professionals',
    rating: 4.7,
  ),
  ServiceCatalogItem(
    name: 'Cleaning',
    subtitle: 'Home deep cleaning',
    asset: AppAssets.serviceCleaning,
    icon: Icons.cleaning_services,
    tint: Color(0xFFEAF7EF),
    professionals: '110+ Professionals',
  ),
  ServiceCatalogItem(
    name: 'Driver',
    subtitle: 'Local travel help',
    asset: AppAssets.serviceDriver,
    icon: Icons.local_taxi,
    tint: Color(0xFFFFEAEA),
    professionals: '60+ Professionals',
    rating: 4.6,
  ),
  ServiceCatalogItem(
    name: 'Photographer',
    subtitle: 'Events & portraits',
    asset: AppAssets.servicePhotographer,
    icon: Icons.photo_camera,
    tint: Color(0xFFEDE7FF),
    professionals: '45+ Professionals',
    rating: 4.7,
  ),
  ServiceCatalogItem(
    name: 'Computer Repair',
    subtitle: 'PC and laptop help',
    asset: AppAssets.serviceComputerRepair,
    icon: Icons.desktop_windows,
    tint: Color(0xFFEAF3FF),
    professionals: '40+ Professionals',
    rating: 4.6,
  ),
  ServiceCatalogItem(
    name: 'Mobile Repair',
    subtitle: 'Screen, battery, software',
    asset: AppAssets.serviceMobileRepair,
    icon: Icons.phone_android,
    tint: Color(0xFFFFE5F2),
    professionals: '50+ Professionals',
    rating: 4.7,
  ),
  ServiceCatalogItem(
    name: 'Pandit Ji',
    subtitle: 'Puja, path, sanskar',
    asset: AppAssets.servicePandit,
    icon: Icons.temple_hindu,
    tint: Color(0xFFFFF1D8),
    professionals: '35+ Professionals',
    rating: 4.9,
  ),
  ServiceCatalogItem(
    name: 'Event Management',
    subtitle: 'Decor and planning',
    asset: AppAssets.serviceEventManagement,
    icon: Icons.celebration,
    tint: Color(0xFFFFE8F3),
    professionals: '30+ Professionals',
  ),
];

const serviceCatalogGroups = [
  ServiceCatalogGroup(
    name: 'Home Services',
    subtitle: 'Repair, maintenance and daily home support',
    imageAsset: AppAssets.categoryHomeServices,
    icon: Icons.home_repair_service,
    tint: Color(0xFFEAF3FF),
    services: [
      ServiceCatalogItem(
        name: 'Plumber',
        subtitle: 'Leakage, taps, pipes',
        asset: AppAssets.servicePlumber,
        icon: Icons.plumbing,
        tint: Color(0xFFE9F2FF),
        professionals: '95+ Professionals',
        rating: 4.7,
      ),
      ServiceCatalogItem(
        name: 'Electrician',
        subtitle: 'Switch, wiring, fittings',
        asset: AppAssets.serviceElectrician,
        icon: Icons.electric_bolt,
        tint: Color(0xFFFFF1D8),
        professionals: '120+ Professionals',
      ),
      ServiceCatalogItem(
        name: 'AC Repair & Service',
        subtitle: 'Service & gas refill',
        asset: AppAssets.serviceAcRepair,
        icon: Icons.ac_unit,
        tint: Color(0xFFF1F3F5),
        professionals: '65+ Professionals',
        rating: 4.7,
      ),
      ServiceCatalogItem(
        name: 'Carpenter',
        subtitle: 'Furniture repair',
        asset: AppAssets.serviceCarpenter,
        icon: Icons.handyman,
        tint: Color(0xFFFFF4EA),
        professionals: '80+ Professionals',
        rating: 4.6,
      ),
      ServiceCatalogItem(
        name: 'Painter',
        subtitle: 'Wall paint & polish',
        asset: AppAssets.servicePainter,
        icon: Icons.format_paint,
        tint: Color(0xFFFFE8E4),
        professionals: '70+ Professionals',
        rating: 4.6,
      ),
      ServiceCatalogItem(
        name: 'Cleaning',
        subtitle: 'Home deep cleaning',
        asset: AppAssets.serviceCleaning,
        icon: Icons.cleaning_services,
        tint: Color(0xFFEAF7EF),
        professionals: '110+ Professionals',
      ),
      ServiceCatalogItem(
        name: 'Computer Repair',
        subtitle: 'PC and laptop help',
        asset: AppAssets.serviceComputerRepair,
        icon: Icons.desktop_windows,
        tint: Color(0xFFEAF3FF),
        professionals: '40+ Professionals',
        rating: 4.6,
      ),
      ServiceCatalogItem(
        name: 'Mobile Repair',
        subtitle: 'Screen, battery, software',
        asset: AppAssets.serviceMobileRepair,
        icon: Icons.phone_android,
        tint: Color(0xFFFFE5F2),
        professionals: '50+ Professionals',
        rating: 4.7,
      ),
      ServiceCatalogItem(
        name: 'Two Wheeler Repair',
        subtitle: 'Bike and scooter help',
        asset: AppAssets.serviceMobileRepair,
        icon: Icons.two_wheeler,
        tint: Color(0xFFFFE5F2),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Four Wheeler Repair',
        subtitle: 'Car service support',
        asset: AppAssets.serviceDriver,
        icon: Icons.directions_car,
        tint: Color(0xFFFFEAEA),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'RO / Water Purifier',
        subtitle: 'Water purifier service',
        asset: AppAssets.serviceCleaning,
        icon: Icons.water_drop,
        tint: Color(0xFFEAF7EF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Driver',
        subtitle: 'Local travel help',
        asset: AppAssets.serviceDriver,
        icon: Icons.local_taxi,
        tint: Color(0xFFFFEAEA),
        professionals: '60+ Professionals',
        rating: 4.6,
      ),
    ],
  ),
  ServiceCatalogGroup(
    name: 'Events',
    subtitle: 'Wedding, puja and celebration services',
    imageAsset: AppAssets.categoryEvents,
    icon: Icons.celebration,
    tint: Color(0xFFFFE8F3),
    services: [
      ServiceCatalogItem(
        name: 'Tent & Light',
        subtitle: 'Tent, lights and event setup',
        asset: AppAssets.serviceEventManagement,
        icon: Icons.festival,
        tint: Color(0xFFFFE8F3),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'DJ',
        subtitle: 'Music and sound setup',
        asset: AppAssets.serviceEventManagement,
        icon: Icons.music_note,
        tint: Color(0xFFEDE7FF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Photographer',
        subtitle: 'Events & portraits',
        asset: AppAssets.servicePhotographer,
        icon: Icons.photo_camera,
        tint: Color(0xFFEDE7FF),
        professionals: '45+ Professionals',
        rating: 4.7,
      ),
      ServiceCatalogItem(
        name: 'Cook',
        subtitle: 'Home and event cooking',
        asset: AppAssets.serviceCook,
        icon: Icons.restaurant,
        tint: Color(0xFFFFF4EA),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Catering',
        subtitle: 'Food service for functions',
        asset: AppAssets.serviceCook,
        icon: Icons.room_service,
        tint: Color(0xFFFFE8E4),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Halwai',
        subtitle: 'Sweets and event food',
        asset: AppAssets.serviceCook,
        icon: Icons.bakery_dining,
        tint: Color(0xFFFFF1D8),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Band / Baaja',
        subtitle: 'Wedding music and procession',
        asset: AppAssets.serviceEventManagement,
        icon: Icons.music_note,
        tint: Color(0xFFEDE7FF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Choreographer',
        subtitle: 'Dance and event performance',
        asset: AppAssets.serviceEventManagement,
        icon: Icons.theater_comedy,
        tint: Color(0xFFFFE8F3),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Pandit Ji',
        subtitle: 'Puja, path, sanskar',
        asset: AppAssets.servicePandit,
        icon: Icons.temple_hindu,
        tint: Color(0xFFFFF1D8),
        professionals: '35+ Professionals',
        rating: 4.9,
      ),
      ServiceCatalogItem(
        name: 'Event Management',
        subtitle: 'Decor and planning',
        asset: AppAssets.serviceEventManagement,
        icon: Icons.celebration,
        tint: Color(0xFFFFE8F3),
        professionals: '30+ Professionals',
      ),
    ],
  ),
  ServiceCatalogGroup(
    name: 'Education',
    subtitle: 'Learning, coaching and classes',
    imageAsset: AppAssets.categoryEducation,
    icon: Icons.school,
    tint: Color(0xFFEAF7EF),
    services: [
      ServiceCatalogItem(
        name: 'School',
        subtitle: 'School admission and support',
        asset: AppAssets.serviceTutor,
        icon: Icons.school,
        tint: Color(0xFFEAF7EF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Home Classes',
        subtitle: 'Home tuition support',
        asset: AppAssets.serviceTutor,
        icon: Icons.menu_book,
        tint: Color(0xFFEAF3FF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Coaching Centre',
        subtitle: 'Subject and exam coaching',
        asset: AppAssets.serviceTutor,
        icon: Icons.cast_for_education,
        tint: Color(0xFFFFF1D8),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Spoken Classes',
        subtitle: 'Language and communication',
        asset: AppAssets.serviceTutor,
        icon: Icons.record_voice_over,
        tint: Color(0xFFEDE7FF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Library',
        subtitle: 'Study space and reading',
        asset: AppAssets.serviceTutor,
        icon: Icons.local_library,
        tint: Color(0xFFF1F3F5),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Colleges',
        subtitle: 'College guidance',
        asset: AppAssets.serviceTutor,
        icon: Icons.account_balance,
        tint: Color(0xFFFFE8E4),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Computer Classes',
        subtitle: 'Computer and digital skills',
        asset: AppAssets.serviceComputerRepair,
        icon: Icons.computer,
        tint: Color(0xFFEAF3FF),
        professionals: 'New category',
        rating: 0,
      ),
    ],
  ),
  ServiceCatalogGroup(
    name: 'Hospital & Care',
    subtitle: 'Medical, hospital and home care',
    imageAsset: AppAssets.categoryHospitalCare,
    icon: Icons.local_hospital,
    tint: Color(0xFFE9F8EF),
    services: [
      ServiceCatalogItem(
        name: 'Medical',
        subtitle: 'Medical store and supplies',
        asset: AppAssets.serviceCleaning,
        icon: Icons.medical_services,
        tint: Color(0xFFE9F8EF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Home Care',
        subtitle: 'Nursing and patient care',
        asset: AppAssets.serviceCleaning,
        icon: Icons.health_and_safety,
        tint: Color(0xFFEAF3FF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Physio',
        subtitle: 'Physiotherapy support',
        asset: AppAssets.serviceCleaning,
        icon: Icons.accessibility_new,
        tint: Color(0xFFFFE8E4),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Hospital',
        subtitle: 'Hospital and clinic help',
        asset: AppAssets.serviceCleaning,
        icon: Icons.apartment,
        tint: Color(0xFFF1F3F5),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Ambulance',
        subtitle: 'Emergency transport',
        asset: AppAssets.serviceDriver,
        icon: Icons.emergency,
        tint: Color(0xFFFFEAEA),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Diagnostic',
        subtitle: 'Lab test and reports',
        asset: AppAssets.serviceCleaning,
        icon: Icons.science,
        tint: Color(0xFFEDE7FF),
        professionals: 'New category',
        rating: 0,
      ),
    ],
  ),
  ServiceCatalogGroup(
    name: 'Property & Rent',
    subtitle: 'Rental homes and property dealing',
    imageAsset: AppAssets.categoryPropertyRent,
    icon: Icons.real_estate_agent,
    tint: Color(0xFFFFF4EA),
    services: [
      ServiceCatalogItem(
        name: 'Rental House',
        subtitle: 'Homes and rooms on rent',
        asset: AppAssets.serviceCarpenter,
        icon: Icons.house,
        tint: Color(0xFFFFF4EA),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Property Dealer',
        subtitle: 'Buy, sell and rent support',
        asset: AppAssets.serviceCarpenter,
        icon: Icons.real_estate_agent,
        tint: Color(0xFFEAF3FF),
        professionals: 'New category',
        rating: 0,
      ),
    ],
  ),
  ServiceCatalogGroup(
    name: 'Food & Stay',
    subtitle: 'Hotels, restaurants and daily food help',
    imageAsset: AppAssets.categoryFoodStay,
    icon: Icons.restaurant,
    tint: Color(0xFFFFF1D8),
    services: [
      ServiceCatalogItem(
        name: 'Hotel',
        subtitle: 'Rooms and stay support',
        asset: AppAssets.serviceCook,
        icon: Icons.hotel,
        tint: Color(0xFFEAF3FF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Restaurant',
        subtitle: 'Food and dining places',
        asset: AppAssets.serviceCook,
        icon: Icons.restaurant,
        tint: Color(0xFFFFF1D8),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Tiffin Service',
        subtitle: 'Daily meal delivery',
        asset: AppAssets.serviceCook,
        icon: Icons.lunch_dining,
        tint: Color(0xFFE9F8EF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Catering',
        subtitle: 'Food service for functions',
        asset: AppAssets.serviceCook,
        icon: Icons.room_service,
        tint: Color(0xFFFFE8E4),
        professionals: 'New category',
        rating: 0,
      ),
    ],
  ),
  ServiceCatalogGroup(
    name: 'Beauty & Wellness',
    subtitle: 'Salon, grooming and fitness support',
    imageAsset: AppAssets.categoryBeautyWellness,
    icon: Icons.spa,
    tint: Color(0xFFFFE5F2),
    services: [
      ServiceCatalogItem(
        name: 'Beauty Parlour',
        subtitle: 'Salon and grooming',
        asset: AppAssets.serviceBeauty,
        icon: Icons.spa,
        tint: Color(0xFFFFE5F2),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Salon at Home',
        subtitle: 'Home grooming service',
        asset: AppAssets.serviceBeauty,
        icon: Icons.face_retouching_natural,
        tint: Color(0xFFFFE8F3),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Yoga Trainer',
        subtitle: 'Yoga and wellness classes',
        asset: AppAssets.serviceBeauty,
        icon: Icons.self_improvement,
        tint: Color(0xFFE9F8EF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Gym / Fitness Trainer',
        subtitle: 'Fitness and personal training',
        asset: AppAssets.serviceBeauty,
        icon: Icons.fitness_center,
        tint: Color(0xFFF1F3F5),
        professionals: 'New category',
        rating: 0,
      ),
    ],
  ),
  ServiceCatalogGroup(
    name: 'Transport',
    subtitle: 'Travel, delivery and vehicle support',
    imageAsset: AppAssets.categoryTransport,
    icon: Icons.local_shipping,
    tint: Color(0xFFFFEAEA),
    services: [
      ServiceCatalogItem(
        name: 'Taxi / Cab',
        subtitle: 'Local and outstation rides',
        asset: AppAssets.serviceDriver,
        icon: Icons.local_taxi,
        tint: Color(0xFFFFEAEA),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Packers & Movers',
        subtitle: 'Home and office shifting',
        asset: AppAssets.serviceDriver,
        icon: Icons.local_shipping,
        tint: Color(0xFFEAF3FF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Courier / Delivery',
        subtitle: 'Parcel and local delivery',
        asset: AppAssets.serviceDriver,
        icon: Icons.delivery_dining,
        tint: Color(0xFFFFF1D8),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Travel Agent',
        subtitle: 'Ticket and trip planning',
        asset: AppAssets.serviceDriver,
        icon: Icons.flight_takeoff,
        tint: Color(0xFFEDE7FF),
        professionals: 'New category',
        rating: 0,
      ),
    ],
  ),
  ServiceCatalogGroup(
    name: 'Legal & Finance',
    subtitle: 'Documents, tax, loan and insurance help',
    imageAsset: AppAssets.categoryLegalFinance,
    icon: Icons.account_balance,
    tint: Color(0xFFEAF3FF),
    services: [
      ServiceCatalogItem(
        name: 'CA / Tax Consultant',
        subtitle: 'Tax filing and accounts',
        asset: AppAssets.serviceComputerRepair,
        icon: Icons.receipt_long,
        tint: Color(0xFFEAF3FF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Lawyer / Legal Help',
        subtitle: 'Legal consultation',
        asset: AppAssets.serviceComputerRepair,
        icon: Icons.gavel,
        tint: Color(0xFFF1F3F5),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Document Writer',
        subtitle: 'Forms, agreements and typing',
        asset: AppAssets.serviceComputerRepair,
        icon: Icons.description,
        tint: Color(0xFFFFF1D8),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Loans',
        subtitle: 'Loan guidance',
        asset: AppAssets.serviceComputerRepair,
        icon: Icons.account_balance_wallet,
        tint: Color(0xFFE9F8EF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Insurance',
        subtitle: 'Insurance support',
        asset: AppAssets.serviceComputerRepair,
        icon: Icons.verified_user,
        tint: Color(0xFFFFF1D8),
        professionals: 'New category',
        rating: 0,
      ),
    ],
  ),
  ServiceCatalogGroup(
    name: 'IT & Digital',
    subtitle: 'Digital work, printing and online services',
    imageAsset: AppAssets.categoryItDigital,
    icon: Icons.devices,
    tint: Color(0xFFEDE7FF),
    services: [
      ServiceCatalogItem(
        name: 'Cyber Cafe',
        subtitle: 'Online forms and printouts',
        asset: AppAssets.serviceComputerRepair,
        icon: Icons.computer,
        tint: Color(0xFFEAF3FF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Printing / Xerox',
        subtitle: 'Print, scan and photocopy',
        asset: AppAssets.serviceComputerRepair,
        icon: Icons.print,
        tint: Color(0xFFF1F3F5),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Web / App Developer',
        subtitle: 'Website and app development',
        asset: AppAssets.serviceComputerRepair,
        icon: Icons.code,
        tint: Color(0xFFEDE7FF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Digital Marketing',
        subtitle: 'Social media and promotion',
        asset: AppAssets.serviceComputerRepair,
        icon: Icons.campaign,
        tint: Color(0xFFFFE8E4),
        professionals: 'New category',
        rating: 0,
      ),
    ],
  ),
  ServiceCatalogGroup(
    name: 'Other Services',
    subtitle: 'Jobs, construction and local business help',
    imageAsset: AppAssets.categoryOtherServices,
    icon: Icons.grid_view_rounded,
    tint: Color(0xFFF1F3F5),
    services: [
      ServiceCatalogItem(
        name: 'Placement & Job',
        subtitle: 'Job and placement support',
        asset: AppAssets.serviceComputerRepair,
        icon: Icons.work,
        tint: Color(0xFFEAF3FF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Construction',
        subtitle: 'Building and civil work',
        asset: AppAssets.serviceCarpenter,
        icon: Icons.construction,
        tint: Color(0xFFFFE8E4),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Architect',
        subtitle: 'Planning and drawing',
        asset: AppAssets.serviceCarpenter,
        icon: Icons.architecture,
        tint: Color(0xFFEDE7FF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Interior & Designer',
        subtitle: 'Interior planning and decor',
        asset: AppAssets.serviceCarpenter,
        icon: Icons.chair,
        tint: Color(0xFFFFF4EA),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Furniture',
        subtitle: 'Furniture work and repair',
        asset: AppAssets.serviceCarpenter,
        icon: Icons.weekend,
        tint: Color(0xFFEAF7EF),
        professionals: 'New category',
        rating: 0,
      ),
      ServiceCatalogItem(
        name: 'Hardware & Accessories',
        subtitle: 'Hardware material support',
        asset: AppAssets.serviceCarpenter,
        icon: Icons.hardware,
        tint: Color(0xFFF1F3F5),
        professionals: 'New category',
        rating: 0,
      ),
    ],
  ),
];

List<ServiceCatalogItem> groupedTakerServices() {
  final services = <ServiceCatalogItem>[];
  final seen = <String>{};
  for (final group in serviceCatalogGroups) {
    for (final service in group.services) {
      if (seen.add(service.name.toLowerCase())) services.add(service);
    }
  }
  return services;
}

ServiceCatalogItem serviceByName(String name) {
  final query = name.toLowerCase();
  return groupedTakerServices().firstWhere(
    (item) =>
        item.name.toLowerCase().contains(query) ||
        query.contains(item.name.toLowerCase()),
    orElse: () => ServiceCatalogItem(
      name: name.trim().isEmpty ? 'Other Service' : name.trim(),
      subtitle: 'Verified local providers',
      asset: serviceAssetFor(name),
      icon: serviceIconFor(name),
      tint: const Color(0xFFFFF1D8),
      professionals: 'New category',
      rating: 0,
    ),
  );
}
