const defaultCategories = [
  {
    defaultKey: 'home-services',
    name: 'Home Services',
    description: 'Repair, maintenance and daily home support.',
    serviceTypes: [
      'Plumber',
      'Electrician',
      'AC Repair & Service',
      'Carpenter',
      'Painter',
      'Cleaning',
      'Computer Repair',
      'Mobile Repair',
      'Two Wheeler Repair',
      'Four Wheeler Repair',
      'RO / Water Purifier',
      'Driver',
    ],
    isActive: true,
  },
  {
    defaultKey: 'events',
    name: 'Events',
    description: 'Wedding, puja and celebration services.',
    serviceTypes: [
      'Tent & Light',
      'DJ',
      'Photographer',
      'Cook',
      'Catering',
      'Halwai',
      'Band / Baaja',
      'Choreographer',
      'Pandit Ji',
      'Event Management',
    ],
    isActive: true,
  },
  {
    defaultKey: 'education',
    name: 'Education',
    description: 'Learning, coaching and classes.',
    serviceTypes: [
      'School',
      'Home Classes',
      'Coaching Centre',
      'Spoken Classes',
      'Library',
      'Colleges',
      'Computer Classes',
    ],
    isActive: true,
  },
  {
    defaultKey: 'hospital-care',
    name: 'Hospital & Care',
    description: 'Medical, hospital and home care.',
    serviceTypes: [
      'Medical',
      'Home Care',
      'Physio',
      'Hospital',
      'Ambulance',
      'Diagnostic',
    ],
    isActive: true,
  },
  {
    defaultKey: 'property-rent',
    name: 'Property & Rent',
    description: 'Rental homes and property dealing.',
    serviceTypes: ['Rental House', 'Property Dealer'],
    isActive: true,
  },
  {
    defaultKey: 'food-stay',
    name: 'Food & Stay',
    description: 'Hotels, restaurants and daily food help.',
    serviceTypes: ['Hotel', 'Restaurant', 'Tiffin Service', 'Catering'],
    isActive: true,
  },
  {
    defaultKey: 'beauty-wellness',
    name: 'Beauty & Wellness',
    description: 'Salon, grooming and fitness support.',
    serviceTypes: [
      'Beauty Parlour',
      'Salon at Home',
      'Yoga Trainer',
      'Gym / Fitness Trainer',
    ],
    isActive: true,
  },
  {
    defaultKey: 'transport',
    name: 'Transport',
    description: 'Travel, delivery and vehicle support.',
    serviceTypes: [
      'Taxi / Cab',
      'Packers & Movers',
      'Courier / Delivery',
      'Travel Agent',
    ],
    isActive: true,
  },
  {
    defaultKey: 'legal-finance',
    name: 'Legal & Finance',
    description: 'Documents, tax, loan and insurance help.',
    serviceTypes: [
      'CA / Tax Consultant',
      'Lawyer / Legal Help',
      'Document Writer',
      'Loans',
      'Insurance',
    ],
    isActive: true,
  },
  {
    defaultKey: 'it-digital',
    name: 'IT & Digital',
    description: 'Digital work, printing and online services.',
    serviceTypes: [
      'Cyber Cafe',
      'Printing / Xerox',
      'Web / App Developer',
      'Digital Marketing',
    ],
    isActive: true,
  },
  {
    defaultKey: 'other-services',
    name: 'Other Services',
    description: 'Jobs, construction and local business help.',
    serviceTypes: [
      'Placement & Job',
      'Construction',
      'Architect',
      'Interior & Designer',
      'Furniture',
      'Hardware & Accessories',
      'Cloth',
    ],
    isActive: true,
  },
];

module.exports = defaultCategories;
